/**
 * Movie REST API for full stack application
 * A backend rest api program for a full stack project
 *
 * OpenAPI spec version: v1
 * Contact: alexandru.i.jurju@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Schema to hold Movie information
 */
export interface Movie {
    id: number;
    /**
     * Title of the movie
     */
    title?: string;
    /**
     * Punch-line of the movie
     */
    tagline?: string;
    /**
     * Small description of the movie
     */
    overview?: string;
    /**
     * Runtime of` the movie in minutes
     */
    runtimeInMinutes?: number;
    releaseStatus?: Movie.ReleaseStatusEnum;
    posterUrl?: string;
    imdbUrl?: string;
    imdbRating?: number;
    trailerUrl?: string;
    releaseDate?: string;
}
export namespace Movie {
    export type ReleaseStatusEnum = 'RELEASED' | 'UPCOMING' | 'OTHER';
    export const ReleaseStatusEnum = {
        RELEASED: 'RELEASED' as ReleaseStatusEnum,
        UPCOMING: 'UPCOMING' as ReleaseStatusEnum,
        OTHER: 'OTHER' as ReleaseStatusEnum
    };
}
