/**
 * Movie REST API for full stack application
 * A backend rest api program for a full stack project
 *
 * OpenAPI spec version: v1
 * Contact: alexandru.i.jurju@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Actor } from './actor';
import { Movie } from './movie';

export interface MovieActor { 
    id?: number;
    movie?: Movie;
    actor?: Actor;
    role?: string;
    displayOrder?: number;
    characterImageUrl?: string;
}