/**
 * Movie REST API for full stack application
 * A backend rest api program for a full stack project
 *
 * OpenAPI spec version: v1
 * Contact: alexandru.i.jurju@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Pageable { 
    page?: number;
    size?: number;
    sort?: Array<string>;
}